# Generated by Django 4.2.7 on 2023-11-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copycap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputG2pk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRealInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HelloWorld',
        ),
    ]
